import '@/css/globals.css'
import '@/css/fontawesome.css'
import '@/css/bootstrap-icons.css'


import type { Metadata } from 'next'
import Script from 'next/script'
import { Providers } from '@/components/Providers/Providers'
import Header from '@/components/Header/Header'
import Footer from '@/components/Footer/Footer'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: "/icon.svg"
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body>
        <Providers>
          <Header />
          <main>
            {children}
          </main>
          <Footer />
        </Providers>
      </body>

      <Script
        src="/js/bootstrap.bundle.min.js"
        strategy="afterInteractive"
      />

      <Script
        src="/js/functions.js"
        strategy="afterInteractive"
      />
    </html>


  )
}
